#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  2 14:49:00 2017

@author: thiru
"""

s = "Hello my name is<firstname> <lastname> child of <father>"
s2 = "Hello my name is <firstname> <lastname> child of <father> <firstname>"
m = {"firstname":"Luke",
     "lastname":"Skywalker",
     "father":"Anakin"}

def fillTemplate(s,m):
    for replacement_tag in m:
        replace_value = m[replacement_tag]
        start_idx = s.find("<{}>".format(replacement_tag))
        while start_idx != -1:
            s = s.replace('<'+replacement_tag+'>',replace_value)
            start_idx = s.find("<{}>".format(replacement_tag))
    return s

def fillTemplatev2(s,m):
    split_string = s.split()
    for i in range(len(split_string)):
        current_word = split_string[i]
        if current_word[1:-1] in m:
            split_string[i] = m[current_word[1:-1]]
    return ' '.join(split_string)

def fillTemplatev3(s,m):
    new_s = ''
    tag = False
    current_tag = ''
    for i in range(len(s)):
        current_character = s[i]
        if tag and current_character != '>':
            current_tag += current_character
            continue
        if current_character == '<':
            tag = True
            current_tag += current_character

        elif current_character == '>':
            current_tag += current_character
            if current_tag[1:-1] in m:
                new_s += m[current_tag[1:-1]]
            else:
                new_s += current_tag
            tag = False
            current_tag = ''
            continue
        else:
            new_s += current_character
    return new_s

print("Test Case 1")
print(fillTemplate(s,m))
print("Test Case 2")
print(fillTemplate(s2,m))
print(fillTemplatev2(s2,m))
print(fillTemplatev3(s2,m))

s3 = "Hello my name is <firstname> <lastname> <potato> child of someone"
fillTemplatev3(s3,m)

def fillTemplateV4(s,m,escape_character="!"):
    new_s = ''
    tag = False
    preceded_by_escape_character = False
    current_tag = ''
    for i in range(len(s)):
        current_character = s[i]
        if current_character == escape_character:
            preceded_by_escape_character = True
            continue

        if tag and current_character != '>':
            current_tag += current_character
            continue
        if current_character == '<':
            tag = True
            if preceded_by_escape_character:
                new_s += current_character
                preceded_by_escape_character = False
                tag = False
                continue

            current_tag += current_character

        elif current_character == '>':
            if preceded_by_escape_character:
                new_s += current_character
                continue

            current_tag += current_character
            if current_tag[1:-1] in m:
                new_s += m[current_tag[1:-1]]
            else:
                new_s += current_tag
            tag = False
            current_tag = ''
            continue
        else:
            new_s += current_character
    return new_s

s4 = "Hello my name is <fir<firstname>stname> !<lastname!> child of someone"
s5 = "Hello my name is <firstname> !<lastname!> child of someone"

fillTemplateV4(s4,m)